const addFooterSection = (
  doc,
  currentY = 700
) => {
  /*
  =========================================
  SAFE FOOTER POSITION
  =========================================
  */

  let footerY = currentY + 25;

  /*
  =========================================
  NEVER CREATE FOOTER-ONLY PAGE
  =========================================
  */

  if (footerY > 730) {
    footerY = 730;
  }

  /*
  =========================================
  FOOTER LINE
  =========================================
  */

  doc
    .moveTo(40, footerY)
    .lineTo(555, footerY)
    .strokeColor("#D9D9D9")
    .lineWidth(1)
    .stroke();

  /*
  =========================================
  FOOTER TEXT
  =========================================
  */

  doc
    .fillColor("#777777")
    .fontSize(10)
    .font("Helvetica")
    .text(
      "Generated by Rubber Scrap Mart",
      40,
      footerY + 15
    );

  doc.text(
    `Generated On: ${new Date().toLocaleDateString()}`,
    360,
    footerY + 15
  );
};

export default addFooterSection;