const addFooterSection = (doc) => {
  /* =========================
     FOOTER LINE
  ========================= */

  doc
    .moveTo(40, 760)
    .lineTo(555, 760)
    .strokeColor("#D9D9D9")
    .lineWidth(1)
    .stroke();

  /* =========================
     FOOTER TEXT
  ========================= */

  doc
    .fillColor("#777777")
    .fontSize(10)
    .font("Helvetica")
    .text(
      "Generated by Rubber Scrap Mart",
      40,
      775
    );

  doc.text(
    `Generated On: ${new Date().toLocaleDateString()}`,
    360,
    775
  );
};

export default addFooterSection;